spin_manifest_version = 2

[application]
name = "challenge-1"
version = "0.1.0"
authors = ["Maxi Capodacqua <kapomaxi1@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "fs"

[component.fs]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "static", destination = "/" }]

[[trigger.http]]
route = "/data"
component = "backend"

[component.backend]
source = "backend/target/backend.wasm"
key_value_stores = ["default"]
[component.backend.build]
command = "npm run build"
workdir = "backend"
